### ISSUE TITLE
when child view add to the next line, calculate child left border error.

### ISSUE THREAD

**Issue by jackjustbj** [LyndonChin/AndroidFlowLayout#2]
FlowLayout.java line 81
childLeft = paddingLeft ---> childLeft = paddingLeft + childWidth + mHorizontalSpacing

**Comment by ylei0514** [comment]
FlowLayout.java
in onMeasure 

if(childLeft + childWidth + paddingRight > myWidth) {
                childLeft = paddingLeft;
                childTop += this.mVerticalSpacing + lineHeight;
                lineHeight = childHeight+this.mVerticalSpacing;
            }else{
                childLeft += childWidth + this.mHorizontalSpacing;
            }

---->
if(childLeft + childWidth + paddingRight > myWidth) {
                childLeft = paddingLeft;
                childTop += this.mVerticalSpacing + lineHeight;
                lineHeight = childHeight+this.mVerticalSpacing;
            }
            childLeft += childWidth + this.mHorizontalSpacing;
